---
title: "Ice-Cream-Dairy-Test"
author: "Emily Yamauchi"
date: "3/2/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r setUp}

urlfile <- 'https://raw.githubusercontent.com/anushnap/icecream/main/csv/dairy_indicators.csv'
df <- read.csv(urlfile)

```


## Dairy vs Dairy Free?

We wanted to know if ice creams that contain dairy have reviews that are different on average from dairy-free reviews.  

```{r hist}

hist(df$rating)


```

```{r boxPlot}

with(df, boxplot(split(rating, contains_dairy)))

```
```{r desc}

dairy_mean <- with(df, tapply(df$rating, df$contains_dairy, mean))
dairy_std <- with(df, tapply(df$rating, df$contains_dairy, sd))
data.frame(dairy_mean, dairy_std)

```


```{r hist_dairy}

hist(df[df$contains_dairy == 'True','rating'])

```


```{r hist_dairy_free}

hist(df[df$contains_dairy == 'False','rating'])


```



```{r aov}

contains_dairy <- df$contains_dairy
rating <- df$rating

aov_dairyfree = aov(rating ~ factor(contains_dairy), data = df)
summary(aov_dairyfree)


```
